name: Add tag to docker image

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-tagged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        env:
          CI: false
        run: |
          npm install
          npm run build
          rm -rf node_modules
          rm -rf package-lock.json
          git checkout --orphan "release-${GITHUB_REF#refs/*/}"
          cd ..
          find . -type f -not -path "./build*" -not -path "./.git*" | xargs git rm -f
          mv build/* build/.well* .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Release ${GITHUB_REF#refs/*/}"
          git push origin "release-${GITHUB_REF#refs/*/}"
